### ISSUE TITLE
Compare Yii2-user modules

### ISSUE THREAD

**Issue by XX** [noogen-projects/yii2-app-start#3]
Compare amnah/yii2-user with dektrium/yii2-user and choose the best of them to use in this project.
https://github.com/amnah/yii2-user
https://github.com/dektrium/yii2-user
http://code.tutsplus.com/tutorials/how-to-program-with-yii2-integrating-user-registration--cms-22974

**Comment by dashadee** [comment]
Added dektrium/yii2-user and dektrium/yii2-rbac modules.
